name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: make test
      - name : Format
        run : make format
      - name: Lint
        run: make lint
      - name: Archive and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml_pipeline-artifacts
          path: ${{ github.workspace }}
        
      - name: Save to repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo GH_TOKEN: "${GH_TOKEN}"
          git config --global user.name 'github-actions'
          git config --local user.email "action@github.com"
          git add rust_llm/src/main.rs
          git commit -m "CICD performed" || echo "ignore commit failure, proceed"
          git push